name: release

on: [workflow_dispatch]

jobs:
 release:
   permissions:
     contents: write
     issues: write
     pull-requests: write
   runs-on: Windows
   steps:
     - name: checkout
       uses: actions/checkout@v2
     - name: install npm
       run: npm install --save-dev semantic-release
     - name: Install dependencies
       run: npm ci
     - name: release
       run: npx semantic-release
       env:
         GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}